name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - uses: actions/checkout@v3
    - name: fastapi_sample
      run: docker build . --file Dockerfile --tag fastapi_sample:test
    - uses: actions/rundocker@v1
    - name: Run docker fastapi_sample
      run: docker run -it --rm -p 1234:1234  -d fastapi_sample
    - uses: actions/pytest@v1
    - name: Pytest
      run: pytest test_app.py
    
